### ISSUE TITLE
Cannot compile proximity_sensor.ino for ROS

### ISSUE THREAD

**Issue by pazeshun** [RoboticMaterials/FA-I-sensor#4]
I use Ubuntu14.04, Arduino IDE 1.8.1 and Teensy LC.
I installed Teensyduino following https://www.pjrc.com/teensy/td_download.html
Error message is as follows:
```
In file included from /home/pazeshun/Arduino/libraries/ros_lib/ros.h:39:0,
                 from /home/pazeshun/catkin_ws/src/FA-I-sensor/force_proximity_ros/src/proximity_sensor/proximity_sensor.ino:24:
/home/pazeshun/Arduino/libraries/ros_lib/ArduinoHardware.h: In constructor 'ArduinoHardware::ArduinoHardware()':
/home/pazeshun/Arduino/libraries/ros_lib/ArduinoHardware.h:70:16: error: cannot convert 'usb_serial_class*' to 'HardwareSerial*' in assignment
       iostream = &Serial;
                ^
```
@Affonso-Gui Do you know anything?

**Comment by Affonso-Gui** [comment]
Ok, I just went through all I've done last year and found what I did to compile. I'll send a pull request for that as soon as possible.

First of all, the way it is now force_proximity_ros acts like a workspace, so let's make it be a package,  then build it and source:
```
cd FA-I-sensor/
mkdir force_proximity_ros_ws/src -p
mv force_proximity_ros/ force_proximity_ros_ws/src -f
cd force_proximity_ros_ws
catkin build;
source devel/setup.bash
```
Then, we need to set up ROS for Arduino IDE following this [link](http://wiki.ros.org/rosserial_arduino/Tutorials/Arduino%20IDE%20Setup).
HOWEVER, in the line `rosrun rosserial_arduino make_libraries.py . ` we add our package to include the custom messages:
```
rosrun rosserial_arduino make_libraries.py . force_proximity_ros
```

Should be able to compile then. If not, please let me know.

**Comment by Affonso-Gui** [comment]
By the way in my case sketchbook was a folder named Arduino under home directory

**Comment by pazeshun** [comment]
Ok, I found how to fix.
The problem is that the serial port is automatically set to USB when Teensy 3.1 is recognized (http://answers.ros.org/question/217986/rosserial-with-teensy-31-comm-port/) in ROS indigo.
We need https://github.com/ros-drivers/rosserial/pull/194 (or more commits), but this fix is included only in jade-devel.
I had to install rosserial from source with jade-devel, remake `ros_lib` by `rosrun rosserial_arduino make_libraries.py .`

**Comment by pazeshun** [comment]
@Affonso-Gui 

> First of all, the way it is now force_proximity_ros acts like a workspace, so let's make it be a package, then build it and source:
> 
> cd FA-I-sensor/
> mkdir force_proximity_ros_ws/src -p
> mv force_proximity_ros/ force_proximity_ros_ws/src -f
> cd force_proximity_ros_ws
> catkin build;
> source devel/setup.bash

Maybe you don't have to move `force_proximity_ros` under `src` of catkin workspace.
You just copy `FA-I-sensor` under `src` like following:
```
cd catkin_ws/src
git clone https://github.com/RoboticMaterials/FA-I-sensor.git
catkin build
```

Also, you don't have to add `force_proximity_ros` expressly.
