### ISSUE TITLE
transparent silicon rubber material

### ISSUE THREAD

**Issue by YutoUchimi** [RoboticMaterials/FA-I-sensor#8]
@correll 
Hello, I am a JSK student.
I want to mold silicon rubber by ourselves.
Could you tell me  which silicon rubber you use?

cc: @k-okada @pazeshun @knorth55

**Comment by correll** [comment]
We are using PDMS or Ecoflex. You can use molds from my onshape profile (linked from my website).

Regards
Nikolaus

**Comment by YutoUchimi** [comment]
I appreciate your kind response.
